# Generated by Django 4.1 on 2025-06-22 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0003_course_image'),
    ]

    operations = [
    ]
